### ISSUE TITLE
Rearranging logos

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/Sansone-Group-Website#8]
There are currently 5 logos on the page next to the video:

![image](https://user-images.githubusercontent.com/3583375/194578131-8ea75626-cd5b-440e-8cc6-300a0880f9b3.png)

Susanna would like these to be made to look better by whatever means necessary, e.g. placing two smaller logos such as Elixir and Stato side-by-side. They are requested to be squeezed into an equivalent width (and presumably height, if possible) to the space taken up by the video. 

She would also like a terms4FAIRskills logo creating and adding, linking to https://terms4fairskills.github.io/.

**Comment by prakhyatox** [comment]
Below are the few designs for new logo for https://terms4fairskills.github.io/
Please let me know feedback.

1) Logo 1
![logo-1](https://user-images.githubusercontent.com/109139583/194845578-11ec96a4-645f-4272-a3f8-9ac2ef82073b.png)

2) Logo 2
![logo-2](https://user-images.githubusercontent.com/109139583/194845633-fd8bda52-5cdf-455d-be4b-e6198ed44965.png)


3) Logo 3
![logo-3](https://user-images.githubusercontent.com/109139583/194845691-d7c57798-14e4-4a60-97ae-4feef3c4134e.png)


4)  Logo 4
![logo-4](https://user-images.githubusercontent.com/109139583/194845731-f533e591-48f9-42e7-b209-9ac8594e8a90.png)

5) Logo 5

![logo-5](https://user-images.githubusercontent.com/109139583/194845811-07e39b68-68c0-43aa-b1f3-9647d748a768.png)

**Comment by knirirr** [comment]
From @SusannaSansone 

> Btw for the logo in the main page, I suggest we remove Tess and only have the current one we run (ISA, FAIRsharing, FAIR Coobook + stato, swo, terms4fairskills; the last 3 should be placed closely since are all ontology); we will add Tess to past project in the new page that I need to create. Once this page is ready, this tile above will no longer link to the individual resources, but to this new page where each resources will get described, and the old one also listed.

**Comment by allysonlister** [comment]
Susanna also asked that, if there is room, to try to squeeze in an ontology for SWO, however please don't do that if there isn't room- it can be added to the additional page Susanna is planning. However we will need a logo.... Here's the link: https://github.com/allysonlister/swo

BTW I also like logo 5 :-)

**Comment by prakhyatox** [comment]
Do we have URL like website for the https://github.com/allysonlister/swo repo ?

**Comment by allysonlister** [comment]
It is likely that we will also need a tiny icon for terms4FAIRskills, e.g. so we can include them inline in text e.g. in the FAIR Cookbook

**Comment by prakhyatox** [comment]
Below are the few designs for new logo for SWO
Please let me know feedback.

1) Logo 1
![SWO-1](https://user-images.githubusercontent.com/109139583/195058195-6ea6a8b2-778b-4758-b435-8b6c55b7485f.png)


2) Logo 2
![SWO-2](https://user-images.githubusercontent.com/109139583/195058247-685eb65f-3aaa-44f2-9c00-1f4887c26906.png)


3) Logo 3
![SWO-3](https://user-images.githubusercontent.com/109139583/195058293-1a1cdcad-08cf-47c6-99f6-0c55a26e09f6.png)

4) Logo 4
![SWO-4](https://user-images.githubusercontent.com/109139583/195058348-3faf54e5-2511-4fbc-8fe8-70d0f2c26c46.png)

**Comment by prakhyatox** [comment]
Updated Logo 4 

![SWO-5](https://user-images.githubusercontent.com/109139583/195098678-d00c2eeb-9e94-4565-a87f-74b8a09debcc.png)

**Comment by prakhyatox** [comment]
New arrangement for logos:

<img width="1346" alt="image" src="https://user-images.githubusercontent.com/109139583/195125552-b6a922ae-9aa1-4900-9f44-24545f94ee2a.png">
